version: "3.8"

services:
  server:
    container_name: nikkorfed
    image: ghcr.io/nikkorfed/nikkorfed:${NODE_ENV}
    build: .
    ports:
      - 127.0.0.1:${PORT}:${PORT}
    restart: unless-stopped
    env_file: .env
